<?php require './Templates/header.phtml';?>
<form action="actualizarjuego/<?= $id ?>" method="POST">
  <div class="mb-3">
    <label for="" class="form-label">Actualizar Juego</label>
    <input type="text" class="form-control" name="nombreactualizarjuego" placeholder="Nombre" required>
    <input type="text" class="form-control" name="generoactualizarjuego" placeholder="Género" required>
    <input type="number" class="form-control" min="1" max="10" name="calificacionactualizarjuego" placeholder="Calificación" required>
  </div>
  <button type="submit" class="btn btn-primary">Actualizar</button>
</form>