<form action="aniadirRequest" method="POST">
  <div class="mb-3">
    <label for="" class="form-label">Añadir Pedido</label>
    <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="nombrejuego" placeholder="nombre del juego" required>
    <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="generojuego" placeholder="genero del juego" required>
    <input type="number" min="1" max="10" class="form-control" id="" aria-describedby="emailHelp" name="calificacionjuego" placeholder="calificacion del juego" required>
  </div>
  <button type="submit" class="btn btn-primary">Añadir</button>
</form>
<form action="actualizarjuego" method="POST">
  <div class="mb-3">
    <label for="" class="form-label">Actualizar Juego</label>
    <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="nombreactualizarjuego" placeholder="Nombre" required>
    <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="generoactualizarjuego" placeholder="Genero" required>
    <input type="number"  min="1" max="10" class="form-control" id="" aria-describedby="emailHelp" name="calificacionactualizarjuego" placeholder="Calificacion" required>
    <input type="number" class="form-control" id="" aria-describedby="emailHelp" name="idactualizarjuego" placeholder="Id" required>
  </div>
  <button type="submit" class="btn btn-primary">Actualizar</button>
</form>
<form action="eliminarjuego" method="POST">
  <div class="mb-3">
    <label for="" class="form-label">Eliminar Juego</label>
    <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="idjuegoeliminar" placeholder="ID" required>
  </div>
  <button type="submit" class="btn btn-primary">Eliminar</button>
</form>