<form action="aniadirRequest" method="POST">
  <div class="mb-3">
    <label for="" class="form-label">Añadir Pedido</label>
    <select name="id_juego" id="">
      <?php foreach($juegos as $juego): ?>
        <option value="<?=$juego->Id_Juego?>"><?=$juego->nombre_juego?></option>
        <?php endforeach ?>
    </select>
    <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="cantidadrequest" placeholder="Cantidad" required>
    <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="preciorequest" placeholder="Precio" required>
  </div>
  <button type="submit" class="btn btn-primary">Añadir</button>
</form>