<form action="actualizarRequestDetails/<?= $id ?>" method="POST">
  <div class="mb-3">
  <label for="" class="form-label">Actualizar Pedido</label>
    <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="cantidadrequest" placeholder="Cantidad" required>
    <input type="text" class="form-control" id="" aria-describedby="emailHelp" name="preciorequest" placeholder="Precio" required>
  <button type="submit" class="btn btn-primary">Actualizar</button>
</form>