<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <base href="<?=BASE_URL?>">
</head>
<body>
    <?php if($_SESSION['ID_USER']): ?>
        <form action="logout">
         <input type="submit" value="logout">
        </form>
    <?php endif ?>

    for($juego as $games){
        <select name="id_juego" id="">
            <option value="<?=$juego->id_juego?>"><?=$juego->nombre_juego?></option>
        </select>
        
    }