<div class="container text-center">
  <div class="row align-items-start">
    <?php foreach($games as $game): ?>
    <div class="col">
    <a href='listarPedido/<?=$game->Id_Juego?>'><?= $game->nombre_juego?> </a>
    <p>GENERO:<?=$game->generos?></p>
    <p>CALIFICACION:<?=$game->califiacion?></p>
    <?php if($this->user): ?>
    <a href="eliminarjuego/<?= $game->Id_Juego ?>" type="button" class='btn btn-danger btn-sm ml-auto'>Borrar</a>
    <a href="mostrarformactualizarjuego/<?= $game->Id_Juego ?>" type="button" class='btn btn-danger btn-sm ml-auto'>ACTUALIZAR JUEGO</a>
    <?php endif ?>
    </div>
    <?php endforeach; ?>
    <?php if($this->user): ?>
        <a href="mostrarformaddjuego">AÑADIR JUEGO</a>
    <?php endif ?>
  </div>
</div>
