<?php require './Templates/header.phtml';?>
<div class="container text-center">
  <div class="row align-items-start">
  <?php require './Templates/form_juegos.phtml' ?>
    <?php foreach($games as $game): ?>
    <div class="col">
    <a href='listarPedido/<?=$game->Id_Juego?>'><?= $game->nombre_juego?> </a>
    <p>Id:<?=$game->Id_Juego?></p>
    <p>GENERO:<?=$game->generos?></p>
    <p>CALIFICACION:<?=$game->califiacion?></p>
    </div>
    <?php endforeach; ?>
  </div>
  <?php require './Templates/form_pedidos.phtml' ?>
</div>
<?php require './Templates/footer.phtml';?>